### ISSUE TITLE
LDAP認証で新規ユーザを作成しようとすると認証失敗して作成できない

### ISSUE THREAD

**Issue by tarumi-neighborhood** [weseek/growi-docker-compose#15]
もし同一事象で、解決されている方がいればご教示ください。

contos7.3にdocument通りの方法でweseek/growi-docker-composeを新規インストールしました。
機能はまだすべて確認できていないのですが、LDAP認証のテストは通っているにも関わらず
ログイン画面では新規ユーザ追加しようとすると認証失敗となり追加できません。
既存ユーザへの関連付けは問題なくできて認証も通ります。
たまにしかサーバを触れず、ログの見どころもわかっていないので、
確認の方法をご教示いただければ応答は悪いかもしれませんがログなども確認いたします。
バグなのか設定が悪いのか不明なのでこちらにかかさせていただきました。
何か情報を共有いただければ幸いです。

LDAPとして使用しているのはADでManager Bind ON
アカウント、パスワードを設定してSearch Filterは(sAMAccountName={{username}})
と設定しています。上述の通りテストは成功、新規以外の認証も成功しています。

**Comment by yuki-takei** [comment]
@tarumi-neighborhood 
やはりもう少し情報がないとなんとも言えないのですが、判断材料になるのは管理画面でのテスト時のログ(TextArea に追加される文字列)、それからコンテナログです。コンテナログは、`docker-compose logs` コマンドのヘルプを参考にしてみてください。

こちらの Issue は一旦 close させていただきます。質問への回答や設定周りサポートは Slack で行っておりますので、上記の情報を添えて書き込んでいただくことでより解決に近づくアドバイスができると思います。https://growi-slackin.weseek.co.jp/ から参加をお願いします。
