### ISSUE TITLE
Bug: ルートへのポータルが作成できない

### ISSUE THREAD

**Issue by atusy** [weseek/growi-docker-compose#18]
はじめまして。 `weseek/growi-docker-compose` をクローンし、docker-composeを利用してGrowiを試験導入していますが、ルートへのポータル作成ができず悩んでいます。

- `localhost:3000` にアクセスし、右上の `Create Portal` ボタンを押すと、エディタ画面に遷移しますが、文字入力する場所がありません。
- 何も入力できていませんが、とりあえず`更新` ボタンを押すと `Error occured HackmdEditor component has not initialized` と出ます。
- 他の場所 `localhost:3000/test/` などにはページを作成できています。
- この時点で `docker-compose.yml` の変更点は `PASSWORD_SEED` のみ

**Comment by yuki-takei** [comment]
@atusy ご報告ありがとうございます。以下確認させてください。

- 完全に新規で GROWI を立ち上げていますか？
    - 以前のバージョンや本家 Crowi のデータを引き継いだなどはないということで合っていますか？
- インストール後、管理画面のカスタマイズから Crowi Classic Behavior への変更を行ったのでしょうか？
    - Create Portal ボタンは、クリーンインストール後のデフォルトである GROWI Simplified Behavior では表示されないはずなので…
- localhost:3000 にアクセスした時に、ブラウザのコンソールおよびサーバー側(app container)のログには特に何もエラーはない感じでしょうか？

よろしくお願いいたします。

**Comment by atusy** [comment]
volumesをバックアップして、下記のコマンドにより初期化したところ、トップページに Welcome to GROWI と表示されることを確認しました。
最悪は記事を移植して対応しようと思います。

```sh
docker-compose down -v
docker-compose up -d
```

**Comment by atusy** [comment]
バックアップファイルの操作をミスして復旧できなくなりました……。
再現もできなくなってしまったので一度Closeします。
お騒がせしました。

**Comment by yuki-takei** [comment]
@atusy お疲れさまです。初期データ生成に失敗した特殊ケースだったんですかね…
再発したらまたお知らせいただければと思います。
