### ISSUE TITLE
HackMDを統合できない

### ISSUE THREAD

**Issue by atusy** [weseek/growi-docker-compose#19]
https://github.com/weseek/growi-docker-compose/issues/18 を受け、HackMDを入れればポータルを作れるのかと思い挑戦しました。
`yaml` ファイルはREADMEに従い以下のように変更しました。
結果、HackMDを直接利用することは可能ですが、GrowiからはHackMDを利用できていません。

```yaml
# docker-compose.yml
environment:
    - HACKMD_URI=http://192.168.5.38:3100
    - HACKMD_URI_FOR_SERVER=http://hackmd:3000

# docker-compose.override.yml
environment:
    - GROWI_URI=http://192.168.5.38:3000
ports:
    - 3100:3000   # localhost only by default
```

**Comment by yuki-takei** [comment]
@atusy #18 の問題は HackMD とは関係ないですね。本体のバグの可能性もあります。

それとは関係なく、もし HackMD を使いたいという事であれば、以下を載せていただけますでしょうか。

-  `docker-compose.yml` と `docker-compose.override.yml` の全文
- GROWI 本体アクセス時のブラウザのコンソールのアウトプット
    - 任意のページアクセス時のログ
    - HackMD エディタを開いた時のログ

**Comment by atusy** [comment]
@yuki-takei 

すみません、トップ以外の任意ページを開いた時はHackMDが統合されていました!
View 編集 の隣にHackMDタブができており、無事起動も確認しました。

トップになぜか表示されている `Create Portal` を押した後の `更新` からは、 `Error occured
HackmdEditor component has not initialized` が出るので勘違いしておりました。
