### ISSUE TITLE
デフォルトのpluginを認識しない

### ISSUE THREAD

**Issue by AnaTofuZ** [weseek/growi-docker-compose#33]
現在 growy をdocker-composeを利用して起動していますが、デフォルトで入っているはずの
- growi-plugin-lsx 
- growi-plugin-pukiwiki-like-linker
これら2つが認識されず、growyの管理コンソールからも有効化することができない状況です。
他に何か必要な情報があれば調査します

**Comment by nasuks** [comment]
つい最近存在を知り、インストールを試みている者です。

私も再現しました。

growi3.5.9では再現せず、growi3.6.1では再現するようです。

Dockerfileのバージョン指定を3.5.9に下げることで、とりあえず問題は回避しました。

なんらかのエンバグでしょうか。いずれにせよ、素晴らしいアプリケーションの開発を続けていただけて感謝しております。

**Comment by yuki-takei** [comment]
@AnaTofuZ @nasuks ご報告ありがとうございます。こちらはチーム内でも認識している既知のバグになります。v3.6.0 から本体が Dockerfile を含むようになり、そのビルドプロセスの実装にミスがあったため、v3.6.1 ではプラグインを認識しないようになってしまっています。

明日中を目処に本体側で修正を行い、v3.6.2 としてリリーする予定です。今しばらくお待ちください。

なお、growi-docker-compose の問題ではないため、こちらの issue は close させていただきます。
