### ISSUE TITLE
HackMD連携で常に新規ページが作成される

### ISSUE THREAD

**Issue by nagashima-w** [weseek/growi-docker-compose#34]
Environment
------------

### Host

| item     | version |
| ---      | --- |
|OS        |Ubuntu 18.04.2 LTS|
|GROWI     |3.4.7 / 3.5.25|
|node.js   |10.16.0|
|npm       |6.9.0|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

### Client

| item     | version |
| ---      | --- |
|OS        |macOS 10.14.6|
|browser   |Google Chrome 79.0.3945.88|

How to reproduce? (再現手順)
---------------------------

- このリポジトリの`docker-compose`と`docker-compose.override`を以下のような形で編集
  - [docker-compose.yml](https://gist.github.com/nagashima-w/2fa3ae389c44aba307fec7683b94d838)
  - [docker-compose.override.yml](https://gist.github.com/nagashima-w/8315394da4af89585802467622ba0841)
- `docker-compose up`

What happens? (症状)
---------------------

- 既存ページのHackMDタブを開く
- 既存ページの内容ではなく、`Start to edit with HackMD`が表示される
- `Start to edit with HackMD`をクリック
- `Page is not found`の表示と共に、新しいページが作成される
  - この時、Docker-ComposeのHackMDコンテナのログには`"GET /new HTTP/1.1" 302 45 "-" "axios/0.19.0"`と表示される
- 新しく作成されたページを適当に編集して保存すると、HackMD側でランダムに生成されたような名前のページが作成される
- 上記で保存したページで再度HackMDタブを開くと、再度`Start to edit with HackMD`が表示される
  - このとき、画面の表示が以下の画像のように、マトリョーシカのような入れ子になってしまう（わかりやすいように数回繰り返しています）
![image](https://user-images.githubusercontent.com/38906424/71400723-f8c0df80-266a-11ea-85b8-0616be078840.png)
- 当初、v3.4.7でこの事象が発生し、Growiのバージョンを3.5.25に変更しても同じ事象が発生します

What is the expected result? (期待される動作)
-------------------------------------------

- 既存ページのHackMDタブを開くと、新規ページが作成されずに既存のページが編集できる
- 画面の表示がマトリョーシカのようにならない

**Comment by yuki-takei** [comment]
@nagashima-w 

https://gist.github.com/nagashima-w/2fa3ae389c44aba307fec7683b94d838#file-docker-compose-yml-L20
この行が違うのではないかと思います。

下記ドキュメントの「動作確認」と「トラブルシュート」のセクションを確認してください。
https://docs.growi.org/ja/admin-guide/admin-cookbook/integrate-with-hackmd.html

**Comment by nagashima-w** [comment]
`HACKMD_URI`に設定するURIはGrowiのURIと同一のものではいけない、ということで理解しました  

現状のdocker-composeファイルでこの箇所に`http://my.domain.com:3100`を指定すると、混在コンテンツとなりブラウザで表示できなくなってしまうため、https-portalコンテナではなくリバースプロキシを採用する等して対処してみたいと思います

ご対応ありがとうございました  
このissueはクローズさせていただきます
