### ISSUE TITLE
Context-Path変更方法

### ISSUE THREAD

**Issue by vuptse** [weseek/growi-docker-compose#41]
Growiを起動させる時に、デフォルトは 「http://localhost:3000」 にて動いているが、
Rootではなく、ポート番号の後ろに任意のContext-Pathを指定し起動させることが可能でしょうか？
例）「http://localhost:3000/growi」 など

**Comment by yuki-takei** [comment]
@vuptse 以前検討はしましたが改修は諦めた経緯があります。

https://github.com/weseek/growi/issues/748
