### ISSUE TITLE
Error occured after install plugin

### ISSUE THREAD

**Issue by ryoma310** [weseek/growi-docker-compose#42]
I made custom plugin and comment out the Dockerfile line below.

```
# install plugins if necessary
# ;;
# ;; NOTE: In GROWI v3 and later,
# ;;       2 of official plugins (growi-plugin-lsx and growi-plugin-pukiwiki-like-linker)
# ;;       are now included in the 'weseek/growi' image.
# ;;       Therefore you will not need following lines except when you install third-party plugins.
# ;;
RUN echo "install plugins" \
 && yarn add \
     growi-plugin-XXX \
     growi-plugin-YYY \
 && echo "done."
# you must rebuild if install plugin at least one
RUN npm run build:prod
```

after build the container, I saw below error in my growi top directory.
```
Error occured in mt
TypeError: Cannot convert undefined or null to object
詳細
    in mt
    in t
    in ForwardRef
    in div
    in div
    in $t
    in t
    in ForwardRef
    in div
    in div
    in p
    in div
    in t
    in $n
    in t
    in ForwardRef
    in p
    in i
    in B
```

how can i fix it?

**Comment by yuki-takei** [comment]
@ryoma310 

As you can see in the NOTE, GROWI v3 or later includes official plugins.

So you can leave the codes commented out.

**Comment by yuki-takei** [comment]
@ryoma310 

> I made custom plugin

Oh, sorry, I coudn't realize your comment.

Coud you setup development environment?

https://docs.growi.org/en/dev/startup-v2/dev-env.html

Dev environment will dump more detail errors.

Further more, if you can read Japanese, docs for developing plugins are here.

https://docs.growi.org/ja/dev/plugin/architecture.html

**Comment by ryoma310** [comment]
thank you for reply!

I just pull and rename your growi-plugin-boilerplate repository, and upload to my repository.
After that, add `yarn add username/repository` to Dockerfile and rebuild by docker-compose.
I think this error comes from version inconsistency of `package.json`.
(I also rename the path in `src/client/js/components/Foo.jsx`)

I haven't setup the development environment.
I will try it and read the documents! thank you!
