### ISSUE TITLE
Question: Use growi docker with growi fork repository

### ISSUE THREAD

**Issue by datvoquoc** [weseek/growi-docker-compose#48]
Hi Yuki.

I like your growi docker compose so much.  It helps me a lot to build growi on Linode ( or any host ).

I just have a question below
- I want to customize growi source ( add feature based on my team's request ). So I think I will fork from https://github.com/weseek/growi 
- So how could I use my fork repository into growi docker ? 

Thanks a lot

**Comment by yuki-takei** [comment]
@datvoquoc Sorry for my late response.

1.  Build your docker image and push to your container repository.
2. Clone weseek/growi-docker-compose repository and rewrite `Dockerfile` to reference your docker image

**Comment by datvoquoc** [comment]
@yuki-takei 
thanks for your anwser. I will try with your guide.
