### ISSUE TITLE
ERROR [4/9] RUN /codimd/apply-growi-agent.sh

### ISSUE THREAD

**Issue by ka-makihara** [weseek/growi-docker-compose#63]
docker-compose up -d
[+] Building 1.4s (8/13)
 => [internal] load build definition from Dockerfile                                                                                                                                               0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                0.0s
 => [internal] load .dockerignore                                                                                                                                                                  0.0s
 => => transferring context: 2B                                                                                                                                                                    0.0s
 => [internal] load metadata for docker.io/hackmdio/hackmd:1.3.0-alpine                                                                                                                            1.0s
 => [internal] load build context                                                                                                                                                                  0.0s
 => => transferring context: 73B                                                                                                                                                                   0.0s
 => [1/9] FROM docker.io/hackmdio/hackmd:1.3.0-alpine@sha256:c255ffc54d132c408786815a0d1013da4031b99afe629b1536f9448c43ddbdc3                                                                      0.0s
 => CACHED [2/9] COPY apply-growi-agent.sh /codimd/apply-growi-agent.sh                                                                                                                            0.0s
 => CACHED [3/9] RUN chmod +x /codimd/apply-growi-agent.sh                                                                                                                                         0.0s
 => ERROR [4/9] RUN /codimd/apply-growi-agent.sh
------
 > [4/9] RUN /codimd/apply-growi-agent.sh:
#0 0.331 /bin/sh: /codimd/apply-growi-agent.sh: not found
------
failed to solve: executor failed running [/bin/sh -c /codimd/apply-growi-agent.sh]: exit code: 127

**Comment by hmpchub** [comment]
私も同様の問題が発生いたしますので、お手数をおかけしますが、ご確認いただきたく存じます。

**Comment by hmpchub** [comment]
本件解決いたしましたので、連携いたします。
私の場合、`apply-growi-agent.sh`の改行コードを`CRLF`に設定しており、Docker 上の Linux 環境で読みこめなかったため、実行できませんでした。
