### ISSUE TITLE
[7.0.1]バージョン表記が7.0.1-RC.0となる

### ISSUE THREAD

**Issue by kometchtech** [weseek/growi-docker-compose#73]
| item     | version |
| ---      | --- |
|OS        ||
|GROWI     |7.0.1-RC.0|
|node.js   |20.12.0|
|npm       |10.5.0|
|yarn      |1.22.19|
|Using Docker|yes|
|Using [growi-docker-compose][growi-docker-compose]|yes|

[growi-docker-compose]: https://github.com/weseek/growi-docker-compose

*(Accessing https://{GROWI_HOST}/admin helps you to fill in above versions)*

# 症状
- docker hubで7.0.1がリリースされたのを確認したあと、READMEにある手順でupdateを試したが、バージョンが**7.0.1-RC.0**となっている。
https://github.com/weseek/growi-docker-compose?tab=readme-ov-file#upgrading-app-container

# 期待する結果
- 7.0.1となる

**Comment by yuki-takei** [comment]
@kometchtech v7.0.1 のビルド時の不具合でした。v7.0.2 以降で修正されています。
